name:                conflate
version:             0.1.0.0
github:              "benweitzman/conflate"
license:             BSD3
author:              "Ben Weitzman"
maintainer:          "benweitzman@gmail.com"
copyright:           "2020 Ben Weitzman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/benweitzman/conflate#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- DataKinds
- DeriveGeneric
- TypeOperators
- RankNTypes
- NamedFieldPuns
- TypeApplications
- StandaloneDeriving
- TypeSynonymInstances
- FlexibleInstances
- DeriveAnyClass
- TypeFamilies
- FlexibleContexts
- OverloadedStrings
- MultiParamTypeClasses
- GADTs
- ScopedTypeVariables
- DefaultSignatures
- FunctionalDependencies

library:
  source-dirs: src

tests:
  conflate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conflate
